export const formDataList = [
  {
    id: 'username',
    label: 'Username',
    grid: 6,
    require: true,
  },
  {
    id: 'password',
    label: 'Password',
    grid: 6,
    require: true,
  },
  {
    id: 'first_name',
    label: 'First Name',
    grid: 4,
    require: true,
  },
  {
    id: 'last_name',
    label: 'Last Name',
    grid: 4,
    require: true,
  },
  {
    id: 'email',
    label: 'Primary Email',
    grid: 6,
    require: true,
  },
  {
    id: 'street1',
    label: 'Address Street',
    grid: 12,
    address: true,
    require: true,
  },
  {
    id: 'street2',
    label: 'Address Street 2',
    grid: 12,
    address: true,
  },
  {
    id: 'city',
    label: 'City',
    grid: 4,
    address: true,
    require: true,
  },
  {
    id: 'state',
    label: 'State',
    grid: 4,
    address: true,
    require: true,
  },
  {
    id: 'zipcode',
    label: 'Zipcode',
    grid: 4,
    address: true,
    require: true,
    maxLength: 5,
  },
];
